var hierarchy =
[
    [ "lucid::ScanlineImage< T, NC, Allocator >::_iterator< Const >", "classlucid_1_1ScanlineImage_1_1__iterator.html", null ],
    [ "lucid::detail::_Viewport< ResizeReaction, KeyReaction, MouseReaction >", "classlucid_1_1detail_1_1__Viewport.html", null ],
    [ "A", "structA.html", null ],
    [ "lucid::AABB_< Container >", "structlucid_1_1AABB__.html", null ],
    [ "ArgvMock", "structArgvMock.html", null ],
    [ "B", "structB.html", null ],
    [ "lucid::argparse::Binding< Converter, nvals >", "classlucid_1_1argparse_1_1Binding.html", null ],
    [ "lucid::argparse::Binding< Converter, -1ul >", "classlucid_1_1argparse_1_1Binding_3_01Converter_00_01-1ul_01_4.html", null ],
    [ "lucid::argparse::Binding< Converter, 1 >", "classlucid_1_1argparse_1_1Binding_3_01Converter_00_011_01_4.html", null ],
    [ "CameraCapture", "structCameraCapture.html", null ],
    [ "lucid::detail::ComposeOp", "structlucid_1_1detail_1_1ComposeOp.html", null ],
    [ "lucid::Constant< Scene, MaterialGetter >", "structlucid_1_1Constant.html", null ],
    [ "lucid::CornellBox", "classlucid_1_1CornellBox.html", null ],
    [ "lucid::Disk_< Container >", "structlucid_1_1Disk__.html", null ],
    [ "lucid::Dispatcher< Tasks >", "classlucid_1_1Dispatcher.html", null ],
    [ "DummyAction", "structDummyAction.html", null ],
    [ "lucid::ElapsedTimer< Clock >", "classlucid_1_1ElapsedTimer.html", null ],
    [ "lucid::CornellBox::MatGetter::BSDF::Eval", "structlucid_1_1CornellBox_1_1MatGetter_1_1BSDF_1_1Eval.html", null ],
    [ "lucid::argparse::FewArgumentsException", "structlucid_1_1argparse_1_1FewArgumentsException.html", null ],
    [ "lucid::Film< Image >", "structlucid_1_1Film.html", null ],
    [ "FilmCapture", "structFilmCapture.html", null ],
    [ "lucid::Logger::Flush", "structlucid_1_1Logger_1_1Flush.html", null ],
    [ "lucid::argparse::detail::fmt_data< Options, Positionals >", "structlucid_1_1argparse_1_1detail_1_1fmt__data.html", null ],
    [ "lucid::detail::fold_wrapper< BinaryOp, LeftOperand >", "structlucid_1_1detail_1_1fold__wrapper.html", null ],
    [ "fmt::formatter< lucid::argparse::detail::fmt_data< std::tuple< Options... >, std::tuple< Positionals... > > >", "structfmt_1_1formatter_3_01lucid_1_1argparse_1_1detail_1_1fmt__data_3_01std_1_1tuple_3_01Options4ef399db7b77ecc75752d8a2ef56743f.html", null ],
    [ "fmt::formatter< lucid::argparse::Option< Key, Converter, nvals > >", "structfmt_1_1formatter_3_01lucid_1_1argparse_1_1Option_3_01Key_00_01Converter_00_01nvals_01_4_01_4.html", null ],
    [ "fmt::formatter< lucid::argparse::Positional< Converter, nvals > >", "structfmt_1_1formatter_3_01lucid_1_1argparse_1_1Positional_3_01Converter_00_01nvals_01_4_01_4.html", null ],
    [ "lucid::detail::_Viewport< ResizeReaction, KeyReaction, MouseReaction >::Handler", "structlucid_1_1detail_1_1__Viewport_1_1Handler.html", null ],
    [ "lucid::argparse::has_repeating_key< Options >", "structlucid_1_1argparse_1_1has__repeating__key.html", null ],
    [ "lucid::argparse::detail::has_repeating_key_impl< Options >", "structlucid_1_1argparse_1_1detail_1_1has__repeating__key__impl.html", null ],
    [ "lucid::argparse::detail::has_repeating_key_impl< First, Rest... >", "structlucid_1_1argparse_1_1detail_1_1has__repeating__key__impl_3_01First_00_01Rest_8_8_8_01_4.html", null ],
    [ "lucid::argparse::detail::has_repeating_key_impl< Last >", "structlucid_1_1argparse_1_1detail_1_1has__repeating__key__impl_3_01Last_01_4.html", null ],
    [ "lucid::detail::helper< T >", "structlucid_1_1detail_1_1helper.html", null ],
    [ "lucid::detail::helper< std::pair< T1, T2 > >", "structlucid_1_1detail_1_1helper_3_01std_1_1pair_3_01T1_00_01T2_01_4_01_4.html", null ],
    [ "lucid::detail::helper< std::tuple< Ts... > >", "structlucid_1_1detail_1_1helper_3_01std_1_1tuple_3_01Ts_8_8_8_01_4_01_4.html", null ],
    [ "lucid::identity", "structlucid_1_1identity.html", null ],
    [ "lucid::Intersection_< Container >", "structlucid_1_1Intersection__.html", null ],
    [ "lucid::detail::ComposeOp::Invoker< LHS, RHS >", "structlucid_1_1detail_1_1ComposeOp_1_1Invoker.html", null ],
    [ "lucid::join< Seq1, Seq2 >", "structlucid_1_1join.html", null ],
    [ "lucid::join< std::integer_sequence< Int, Ints1... >, std::integer_sequence< Int, Ints2... > >", "structlucid_1_1join_3_01std_1_1integer__sequence_3_01Int_00_01Ints1_8_8_8_01_4_00_01std_1_1integba06621a7292dceeb543aaccf5f7d012.html", null ],
    [ "lucid::join< typelist< Ts1... >, typelist< Ts2... > >", "structlucid_1_1join_3_01typelist_3_01Ts1_8_8_8_01_4_00_01typelist_3_01Ts2_8_8_8_01_4_01_4.html", null ],
    [ "lucid::argparse::Key< KeyType >", "structlucid_1_1argparse_1_1Key.html", null ],
    [ "lucid::argparse::key_index< Key, Options >", "structlucid_1_1argparse_1_1key__index.html", null ],
    [ "lucid::argparse::key_index< Key, std::tuple< Options... > >", "structlucid_1_1argparse_1_1key__index_3_01Key_00_01std_1_1tuple_3_01Options_8_8_8_01_4_01_4.html", null ],
    [ "lucid::argparse::detail::key_index_impl< Key, Idx, Options >", "structlucid_1_1argparse_1_1detail_1_1key__index__impl.html", null ],
    [ "lucid::argparse::detail::key_index_impl< Key, Idx >", "structlucid_1_1argparse_1_1detail_1_1key__index__impl_3_01Key_00_01Idx_01_4.html", null ],
    [ "lucid::argparse::detail::key_index_impl< Key, Idx, _Option, Rest... >", "structlucid_1_1argparse_1_1detail_1_1key__index__impl_3_01Key_00_01Idx_00_01__Option_00_01Rest_8_8_8_01_4.html", null ],
    [ "lucid::argparse::KeyCharSeq", "structlucid_1_1argparse_1_1KeyCharSeq.html", null ],
    [ "lucid::argparse::KeyException< Key >", "structlucid_1_1argparse_1_1KeyException.html", null ],
    [ "lucid::argparse::KeywordValue", "structlucid_1_1argparse_1_1KeywordValue.html", null ],
    [ "lucid::LogFile", "structlucid_1_1LogFile.html", null ],
    [ "lucid::Logger", "classlucid_1_1Logger.html", null ],
    [ "lucid::CornellBox::MatGetter", "classlucid_1_1CornellBox_1_1MatGetter.html", null ],
    [ "lucid::Matrix< T, M, N, Container >", "classlucid_1_1Matrix.html", null ],
    [ "lucid::Matrix< std::array >", "classlucid_1_1Matrix.html", null ],
    [ "lucid::argparse::NeedHelpException", "structlucid_1_1argparse_1_1NeedHelpException.html", null ],
    [ "lucid::argparse::Option< Key, Converter, nvals >", "structlucid_1_1argparse_1_1Option.html", null ],
    [ "lucid::argparse::Option< Key, Converter, -1ul >", "structlucid_1_1argparse_1_1Option_3_01Key_00_01Converter_00_01-1ul_01_4.html", null ],
    [ "lucid::out_of_range", "structlucid_1_1out__of__range.html", null ],
    [ "lucid::argparse::ParseResults< Bindings, Options >", "structlucid_1_1argparse_1_1ParseResults.html", null ],
    [ "lucid::argparse::ParseResults< std::pair< OptBindings, PosBindings >, Options >", "structlucid_1_1argparse_1_1ParseResults_3_01std_1_1pair_3_01OptBindings_00_01PosBindings_01_4_00_01Options_01_4.html", null ],
    [ "lucid::argparse::ParseResults< std::tuple< OptBindings... >, Options >", "structlucid_1_1argparse_1_1ParseResults_3_01std_1_1tuple_3_01OptBindings_8_8_8_01_4_00_01Options_01_4.html", null ],
    [ "lucid::PathTracer_< RandomEngine, Scene, MaterialGetter >", "structlucid_1_1PathTracer__.html", null ],
    [ "lucid::perspective", "structlucid_1_1perspective.html", null ],
    [ "lucid::PixelReset< Filter >", "structlucid_1_1PixelReset.html", null ],
    [ "lucid::PixelUpdate< Filter >", "structlucid_1_1PixelUpdate.html", null ],
    [ "lucid::argparse::Positional< Converter, nvals >", "structlucid_1_1argparse_1_1Positional.html", null ],
    [ "lucid::argparse::PositionalBinding< Converter, nvals >", "classlucid_1_1argparse_1_1PositionalBinding.html", null ],
    [ "lucid::argparse::PositionalBinding< Converter, 1 >", "classlucid_1_1argparse_1_1PositionalBinding_3_01Converter_00_011_01_4.html", null ],
    [ "lucid::RandomDistribution< T, Distribution >", "classlucid_1_1RandomDistribution.html", null ],
    [ "lucid::RandomDistribution< bool >", "classlucid_1_1RandomDistribution_3_01bool_01_4.html", null ],
    [ "lucid::Ray_< Container >", "structlucid_1_1Ray__.html", null ],
    [ "lucid::Ray_< std::array >", "structlucid_1_1Ray__.html", null ],
    [ "lucid::repeat_integer< N, Int, Vals >", "structlucid_1_1repeat__integer.html", null ],
    [ "lucid::repeat_integer< 1, Int, Vals... >", "structlucid_1_1repeat__integer_3_011_00_01Int_00_01Vals_8_8_8_01_4.html", null ],
    [ "lucid::repeat_type< N, Ts >", "structlucid_1_1repeat__type.html", null ],
    [ "lucid::repeat_type< 1, Ts... >", "structlucid_1_1repeat__type_3_011_00_01Ts_8_8_8_01_4.html", null ],
    [ "lucid::CornellBox::MatGetter::BSDF::Sample", "structlucid_1_1CornellBox_1_1MatGetter_1_1BSDF_1_1Sample.html", null ],
    [ "lucid::scanline_iterator", "structlucid_1_1scanline__iterator.html", null ],
    [ "lucid::ScanlineImage< T, NC, Allocator >", "classlucid_1_1ScanlineImage.html", null ],
    [ "lucid::ScanlineImage< float, 4 >", "classlucid_1_1ScanlineImage.html", null ],
    [ "lucid::perspective::shoot", "structlucid_1_1perspective_1_1shoot.html", null ],
    [ "lucid::Sphere_< Container >", "structlucid_1_1Sphere__.html", null ],
    [ "lucid::argparse::StandardErrorHandler< Options, Positionals >", "classlucid_1_1argparse_1_1StandardErrorHandler.html", null ],
    [ "lucid::StaticSpan< T, N >", "classlucid_1_1StaticSpan.html", null ],
    [ "lucid::steady_tuple< Ts >", "classlucid_1_1steady__tuple.html", null ],
    [ "lucid::detail::steady_tuple_impl< Idxs, Ts >", "classlucid_1_1detail_1_1steady__tuple__impl.html", null ],
    [ "lucid::detail::steady_tuple_impl< Idxs, Ts... >", "classlucid_1_1detail_1_1steady__tuple__impl.html", null ],
    [ "lucid::detail::steady_tuple_leaf< I, T >", "classlucid_1_1detail_1_1steady__tuple__leaf.html", null ],
    [ "lucid::detail::steady_tuple_leaf< Idxs, Ts >", "classlucid_1_1detail_1_1steady__tuple__leaf.html", [
      [ "lucid::detail::steady_tuple_impl< std::index_sequence< Idxs... >, Ts... >", "classlucid_1_1detail_1_1steady__tuple__impl_3_01std_1_1index__sequence_3_01Idxs_8_8_8_01_4_00_01Ts_8_8_8_01_4.html", null ]
    ] ],
    [ "TimerTask< Duration, Value >", "structTimerTask.html", null ],
    [ "to_unsigned", "structto__unsigned.html", null ],
    [ "lucid::TriangleFilter", "structlucid_1_1TriangleFilter.html", null ],
    [ "std::tuple_element< I, lucid::Matrix< T, M, N, Container > >", "classstd_1_1tuple__element_3_01I_00_01lucid_1_1Matrix_3_01T_00_01M_00_01N_00_01Container_01_4_01_4.html", null ],
    [ "std::tuple_element< I, lucid::StaticSpan< T, N > >", "classstd_1_1tuple__element_3_01I_00_01lucid_1_1StaticSpan_3_01T_00_01N_01_4_01_4.html", null ],
    [ "std::tuple_element< I, lucid::Vector< T, N, Container > >", "classstd_1_1tuple__element_3_01I_00_01lucid_1_1Vector_3_01T_00_01N_00_01Container_01_4_01_4.html", null ],
    [ "std::tuple_size< lucid::Matrix< T, M, N, Container > >", "classstd_1_1tuple__size_3_01lucid_1_1Matrix_3_01T_00_01M_00_01N_00_01Container_01_4_01_4.html", null ],
    [ "std::tuple_size< lucid::StaticSpan< T, N > >", "classstd_1_1tuple__size_3_01lucid_1_1StaticSpan_3_01T_00_01N_01_4_01_4.html", null ],
    [ "std::tuple_size< lucid::Vector< T, N, Container > >", "classstd_1_1tuple__size_3_01lucid_1_1Vector_3_01T_00_01N_00_01Container_01_4_01_4.html", null ],
    [ "lucid::typelist< Ts >", "structlucid_1_1typelist.html", null ],
    [ "lucid::argparse::UnexpectedValue", "structlucid_1_1argparse_1_1UnexpectedValue.html", null ],
    [ "lucid::uniform_init", "structlucid_1_1uniform__init.html", null ],
    [ "lucid::argparse::Value", "structlucid_1_1argparse_1_1Value.html", null ],
    [ "lucid::Vector< T, N, Container >", "classlucid_1_1Vector.html", null ],
    [ "lucid::Vector< Container >", "classlucid_1_1Vector.html", null ],
    [ "lucid::Vector< std::array >", "classlucid_1_1Vector.html", null ],
    [ "view_facade", null, [
      [ "lucid::argparse::ArgsRange", "classlucid_1_1argparse_1_1ArgsRange.html", null ]
    ] ],
    [ "lucid::argparse::Visitor< OptDesc, PosDesc >", "classlucid_1_1argparse_1_1Visitor.html", null ],
    [ "lucid::window_scanline_iterator", "structlucid_1_1window__scanline__iterator.html", null ]
];